name: Repo Sync

on:
  schedule:
  - cron:  "47 5 * * *"
  issues:
    types: [closed]

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    env:
      GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa"
    steps:
    - uses: actions/checkout@v2
    - name: setup ssh key
      run: |
        mkdir -p  ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600  ~/.ssh/id_rsa
        echo $HOME
        echo $GITHUB_WORKSPACE
      shell: bash
      env:
        SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time
    - name: Clone from target repo
      run: |
        git clone --depth 1 git@github.com:KusakabeSi/dn42-registry.git ~/work/old_repo
    - name: Pull from source repo
      run: |
        cd  ~/work/old_repo
        git remote set-url origin git@git.dn42.dev:dn42/registry.git
        git pull -f
      shell: bash
    - name: Push back to target repo
      run: |
        cd  ~/work/old_repo
        git remote set-url origin git@github.com:KusakabeSi/dn42-registry.git ~/work/old_repo
        git push -f
      shell: bash
    - name: wrtie something to prevent github action get stopped
      run: |
        echo ${{ steps.current-time.outputs.time }} > $GITHUB_WORKSPACE/sync
      shell: bash
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
        author_email: si@kskb.eu.org
        author_name: KusakabeSi
        message: sync at ${{ steps.current-time.outputs.time }}
